# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 06:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='status',
        ),
        migrations.AddField(
            model_name='truck',
            name='dayhour',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='truck',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 23, 6, 25, 53, 844534)),
        ),
        migrations.AddField(
            model_name='truck',
            name='food_item',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='truck',
            name='status',
            field=models.CharField(default='REQUESTED', max_length=50),
        ),
    ]
